apiVersion: batch/v1
kind: CronJob
metadata:
  generation: 3
  name: getting-authors-from-solr
  namespace: linkedcat
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - solr
                  topologyKey: kubernetes.io/hostname
          containers:
            - command:
                - php
                - /var/www/server/services/getLinkedCatAuthors.php
                - '--force-refresh'
              image: ghcr.io/acdh-oeaw/linkedcat-deployment/okm-headstart:latest
              imagePullPolicy: Always
              name: getting-authors-from-solr
              securityContext:
                allowPrivilegeEscalation: true
                capabilities: {}
                privileged: true
                readOnlyRootFilesystem: false
                runAsUser: 0
              stdin: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              tty: true
              volumeMounts:
                - mountPath: /var/www/server/storage/
                  name: sqlite-data
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          volumes:
            - name: sqlite-data
              persistentVolumeClaim:
                claimName: sqlite-data
  schedule: 00 8 * * *
  successfulJobsHistoryLimit: 3
  suspend: false

