apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: linkedcat-backup
  namespace: linkedcat
spec:
  schedule: "20 3 * * *" 
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - solr
                  topologyKey: kubernetes.io/hostname
          containers:
          - name: linkedcat-backup
            image: quay.io/toolbx-images/alpine-toolbox:3.18
            imagePullPolicy: IfNotPresent
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File  
            volumeMounts:
            - mountPath: /backup
              name: linkedcat-backup           
            - mountPath: /solr-data
              name: solr-data  
            - mountPath: /sqlite-data
              name: sqlite-data               
            command:
            - /bin/sh
            - -c
            - find /backup -type f -mtime +10 -delete && cd / && tar -czvf /backup/linkedcat-backup-$(date +"%Y_%m_%d_%H_%M").tar.gz solr-data sqlite-data  
          volumes:
          - name: linkedcat-backup
            persistentVolumeClaim:
              claimName: linkedcat-backup
          - name: solr-data
            persistentVolumeClaim:
              claimName: solr-data
          - name: sqlite-data
            persistentVolumeClaim:
              claimName: sqlite-data
          restartPolicy: OnFailure