name: Deploy Linkedcat

on:
  push:
    branches: [main]

jobs:
#  build:
#    name: Build OKM Headstart
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2 
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and push OKM Headstart
#        uses: docker/build-push-action@v3
#        with:
#          context: okm-headstart/.
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#            ghcr.io/acdh-oeaw/linkedcat-deployment/okm-headstart:latest
  deploy:
    runs-on: ubuntu-latest
#    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Deploy
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.C2_KUBE_CONFIG }}
        kubectl-version: v1.21.8
    # Delete previous ConfigMaps
    - run: |
        kubectl -n linkedcat delete configmap config-local-ini
        kubectl -n linkedcat delete configmap config-js
        kubectl -n linkedcat delete configmap webpack-config-js
        kubectl -n linkedcat delete configmap supervisor-config
    # Create ConfigMaps from the configuration files
    - run: |
        kubectl -n linkedcat create configmap config-local-ini --from-file=./config/config_local.ini
        kubectl -n linkedcat create configmap config-js --from-file=./config/config.js
        kubectl -n linkedcat create configmap webpack-config-js --from-file=./config/webpack.config.js
        kubectl -n linkedcat create configmap supervisor-config --from-file=./config/supervisord.conf

    # Create all the Kubernetes deployments, services and related objects
    - run: kubectl -n linkedcat apply -f Kubernetes/
